// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDOBDFEQse2Nyv4z2bx5UWymFI81EyUUU',
    appId: '1:884542559214:web:3a506cb810ae98113c74ff',
    messagingSenderId: '884542559214',
    projectId: 'flutter-application-1-3da78',
    authDomain: 'flutter-application-1-3da78.firebaseapp.com',
    storageBucket: 'flutter-application-1-3da78.firebasestorage.app',
    measurementId: 'G-N4QGQKS5MB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXv9LBzxiSxEfHYCPhzUUELGT2_9tQg8o',
    appId: '1:884542559214:android:7408e2acd18b33b53c74ff',
    messagingSenderId: '884542559214',
    projectId: 'flutter-application-1-3da78',
    storageBucket: 'flutter-application-1-3da78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDblpeWJHHcRIXMGnkGVDldzIfDpZqUsmc',
    appId: '1:884542559214:ios:20672030dbe03a7b3c74ff',
    messagingSenderId: '884542559214',
    projectId: 'flutter-application-1-3da78',
    storageBucket: 'flutter-application-1-3da78.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDblpeWJHHcRIXMGnkGVDldzIfDpZqUsmc',
    appId: '1:884542559214:ios:20672030dbe03a7b3c74ff',
    messagingSenderId: '884542559214',
    projectId: 'flutter-application-1-3da78',
    storageBucket: 'flutter-application-1-3da78.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDOBDFEQse2Nyv4z2bx5UWymFI81EyUUU',
    appId: '1:884542559214:web:0563c2c9a1e57b903c74ff',
    messagingSenderId: '884542559214',
    projectId: 'flutter-application-1-3da78',
    authDomain: 'flutter-application-1-3da78.firebaseapp.com',
    storageBucket: 'flutter-application-1-3da78.firebasestorage.app',
    measurementId: 'G-ZHBH6NE3XD',
  );
}
